version: '0.2'

phases:
  install:
    commands:
      - npm i -g aws-cdk
      - cdk --version
  build: 
    commands: 
      - env
      - cd api
      - npm i
      - cdk synth
      - ls
artifacts: 
  files:
    - 'api/cdk.out/*'